### ISSUE TITLE
ImportError: No module named 'music.functions'

### ISSUE THREAD

**Issue by sophia-corvaia** [ttm/music#6]
Hi everyone!

I have a little problem with import music instruction. When I run my program I found this error:

Traceback (most recent call last):
  File "MusicTypeGenerator.py", line 3, in <module>
    from dataset_generator import DatasetGenerator
  File "/home/sophy0295/magenta/magenta/models/music_vae/Tesi_Codice/dataset_generator.py", line 9, in <module>
    import music
  File "/home/sophy0295/.local/lib/python3.5/site-packages/music/music/__init__.py", line 1, in <module>
    from .utils import H
  File "/home/sophy0295/.local/lib/python3.5/site-packages/music/music/utils.py", line 3, in <module>
    from .functions import *
ImportError: No module named 'music.functions'

Can you help me? Thank you so much :)

**Comment by ttm** [comment]
Hi @sophia-corvaia , my apologies for taking long to reply. I have updated the package a few minutes ago. May you try it again? In case it fails, please write your python version and OS. Cheers!
