### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by RomeoAvagyan** [ttm/music#7]
Traceback (most recent call last):   
  File "test.py", line 6, in <module>                                      
    from music import *              
  File "/usr/local/lib/python3.6/dist-packages/music/__init__.py", line 2, in <module>
    from . import utils, tables, synths, effects, structures, singing      
ImportError: cannot import name 'structures'

**Comment by ttm** [comment]
Hi @RomeoAvagyan, I have updated the package a few minutes ago. May you try it again? In case it fails, please write your python version and OS. Cheers!
